### ISSUE TITLE
Chat doesn't default to lobby chat if opening a direct link

### ISSUE THREAD

**Issue by Rand404** [TF2Stadium/QA#13] opened 2015-11-25 21:37 UTC
If you follow a direct link to a lobby (tf2stadium.com/lobby/XX) the chat remains on the general chat instead of defaulting to the lobby chat.

**Comment by mcapu** [comment] 2015-11-28 01:38
(Duplicate of #9)

**Closed as completed** 2015-12-01 19:24 UTC
