### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by Haarolean** [TF2Stadium/QA#24] opened 2016-01-29 22:03 UTC
That's my filter:
![pcc6usl](https://cloud.githubusercontent.com/assets/1494347/12689317/887be356-c6f5-11e5-9ca8-2014f449dab3.png)
And I don't see eu lobby:
![qhhvxh9](https://cloud.githubusercontent.com/assets/1494347/12689320/909f465e-c6f5-11e5-8598-1ec3c54a5ac9.png)

**Comment by gpittarelli** [comment] 2016-02-04 19:24
I can't reproduce this. Could you verify that this isn't because that mumble is "non-mumble-required" and you may have had the "mumble required" option selected? (Under Misc)

**Comment by Haarolean** [comment] 2016-02-04 20:08
@gpittarelli you didn't understand me.
Now, there are no lobbies and filters are disabled, but I still see 'maybe change filter settings?' message. That won't help I guess, if there are no lobbies :)

**Comment by gpittarelli** [comment] 2016-02-04 20:39
I don't see how I misunderstood your original issue.

For this:

> Now, there are no lobbies and filters are disabled, but I still see 'maybe change filter settings?' message. That won't help I guess, if there are no lobbies :)

This is now fixed by https://github.com/TF2Stadium/Frontend/pull/177

It looks like before if there are really no lobbies, otherwise it will show the total number of lobbies:

![hidden-lobbies](https://cloud.githubusercontent.com/assets/1004194/12828576/b0b8618e-cb53-11e5-884c-34d63380c7a9.png)

(In that screenshot, the 1 active lobby is filtered out by one of the other filter options)

**Closed as completed** 2016-02-04 20:39 UTC
Labels: frontend

**Comment by Haarolean** [comment] 2016-02-04 21:07
ok, fixed now. Good job!
